In [30]:
from datasets import load_dataset
import json
import pandas as pd

# Download taidng/UIT-ViQuAD2.0

In [3]:
ds = load_dataset("taidng/UIT-ViQuAD2.0")

len(ds)

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/5.20M [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/735k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/28454 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/3814 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/7301 [00:00<?, ? examples/s]

3

In [ ]:
output_dir = '../data/raw/UIT-ViQuAD2.0/'

for split in ('train', 'validation', 'test') :
    data = ds[split]

    output_filename = output_dir + split + '.jsonl'
    with open(output_filename, 'w') as jsonl_file :
        for d in data :
            json_string = json.dumps(d, ensure_ascii=False)
            jsonl_file.write(json_string + '\n')

    print("Successfully write to " + output_filename)

Successfully write to ../data/UIT-ViQuAD2.0/train.jsonl
Successfully write to ../data/UIT-ViQuAD2.0/validation.jsonl
Successfully write to ../data/UIT-ViQuAD2.0/test.jsonl

# Download anti-ai-community/tydiqa-goldp-vietnamese

In [20]:
# Load corpuses and queries

corpuses = load_dataset("anti-ai-community/tydiqa-goldp-vietnamese", "corpus")
queries = load_dataset("anti-ai-community/tydiqa-goldp-vietnamese", "query")

# Data only contains test split
corpuses, queries = corpuses['test'], queries['test']

len(corpuses), len(queries)

(3858, 440)

In [21]:
corpuses[0]

{'passage_id': 0,
 'passage': 'Hiệp ước Lateran (tiếng Ý: Patti Lateranensi; tiếng Latin: Pacta Lateranensia) là một trong những Hiệp ước Lateran năm 1929 hoặc Hiệp định Lateran, các thỏa thuận được thực hiện vào năm 1929 giữa Vương quốc Ý và Tòa Thánh, giải quyết "Vấn đề La Mã".'}

In [24]:
base_output_dir = '../data/raw/tydiqa-goldp-vietnamese/'

corpus_output_filename = base_output_dir + 'corpuses' + '.jsonl'
with open(corpus_output_filename, 'w') as jsonl_file :
    for c in corpuses :
        json_string = json.dumps(c, ensure_ascii=False)
        jsonl_file.write(json_string + '\n')

print("Successfully write to " + corpus_output_filename)

Successfully write to ../data/raw/tydiqa-goldp-vietnamese/corpuses.jsonl

In [25]:
queries_output_filename = base_output_dir + 'queries' + '.jsonl'
with open(queries_output_filename, 'w') as jsonl_file :
    for q in queries :
        json_string = json.dumps(q, ensure_ascii=False)
        jsonl_file.write(json_string + '\n')

print("Successfully write to " + queries_output_filename)

Successfully write to ../data/raw/tydiqa-goldp-vietnamese/queries.jsonl

# Download mmarco-EnVi-subdataset

In [32]:
# Login using e.g. `huggingface-cli login` to access this dataset
ds = load_dataset("tiennv/mmarco-EnVi-subdataset")

In [33]:
ds = pd.DataFrame(ds['train'])

ds

,query,positive,negatives
0,Định nghĩa msds là gì,WHMIS 1988 - Bảng Dữ liệu An toàn Vật liệu (MS...,[thông tin nhận dạng sản phẩm (tên sản phẩm) đ...
1,meaning of the name mahlah,The meaning of the name Mahlah is Sickness The...,[Latin Meaning: The name Corbin is a Latin bab...
2,hội đồng nhập cư mỹ là gì,Đánh giá: 5 sao 1 người thấy nhận xét này hữu ...,[Giới thiệu về Hội đồng Y tế Hoa Kỳ Với khu vự...
3,làm thế nào để tạo ra một tấm kim loại phanh,1 Sử dụng kim loại nặng hơn để có một phanh hã...,[Việc bóp cần của phanh đĩa thủy lực sẽ tác độ...
4,bao nhiêu kb tính bằng gb,Có bao nhiêu Kilobyte trong một Gigabyte 1 Gig...,[* Mô hình này không được bán ở Mỹ IPhone 5 (C...
...,...,...,...
37808,where can i find an aloe plant,"The plant Agave americana, which is sometimes ...",[Aloe vera (aloe vera) Aloe vera has been desc...
37809,một bác sĩ siêu âm y tế kiếm được bao nhiêu mộ...,Tỷ lệ trả hàng giờ và mức lương Theo Cục Thống...,[Mức lương của bác sĩ siêu âm tim theo các thà...
37810,what is a cdu in hospital,CDU where I work is where people are observed ...,[Northside Hospital - Atlanta | Northside Hosp...
37811,hành vi mất trật tự arkansas là gì,Arkansas: Hành vi gây rối trật tự là tội nhẹ l...,[Một hành vi phạm tội có thể truy tố ở New Jer...
37812,what is georgia's state bird and flower,A Resolution Designating the Brown Thrasher as...,[Wear a flower behind your ear This is the mos...

In [36]:
english_words = ['of', 'an', 'the']
english_pattern = '|'.join(english_words)

vietnamese_ds = ds[~ds['positive'].str.contains(english_pattern)]

vietnamese_ds[:8]

,query,positive,negatives
2,hội đồng nhập cư mỹ là gì,Đánh giá: 5 sao 1 người thấy nhận xét này hữu ...,[Giới thiệu về Hội đồng Y tế Hoa Kỳ Với khu vự...
4,bao nhiêu kb tính bằng gb,Có bao nhiêu Kilobyte trong một Gigabyte 1 Gig...,[* Mô hình này không được bán ở Mỹ IPhone 5 (C...
6,loại nguyên tố nào là erbium,Erbium không bao giờ được tìm thấy trong tự nh...,[Bằng cách làm việc ngược lại thông qua một tr...
9,mấy giờ mở cửa walgreens,Các ngày trong tuần: Giờ làm việc của cửa hàng...,"[Công ty Walgreen (đơn giản là Walgreens, hoặc..."
10,xe chở rác nặng bao nhiêu,Bao nhiêu chất thải “nặng” trong xe tải hoặc b...,[Một chiếc xe tải quái vật phải nặng tối thiểu...
16,xác định cơ chủ vận,Đối kháng Cơ đối kháng là một cơ có khả năng c...,"[Freebase (0,00 0 phiếu bầu) Đánh giá định ngh..."
17,cách bắt đầu kinh doanh dịch vụ chải lông cho ...,"Nếu vậy, hãy xin giấy phép thích hợp 5 Liên hệ...",[Bắt đầu lên giá Chi phí khởi động trung bình ...
24,afis đề cập đến điều gì trong pháp y,Tìm kiếm định nghĩa của AFIS? Tìm hiểu ý nghĩa...,[Vai trò của Pháp y trong việc giải quyết tội ...

In [ ]:
base_output_dir = '../data/raw/mmarco-EnVi-subdataset/'

json_vietnamese_df = vietnamese_ds.to_json()

output_filename = base_output_dir + 'train' + '.jsonl'
with open(output_filename, 'w') as jsonl_file :
    for line in vietnamese_ds :
        json_string = json.dumps(line, ensure_ascii=False)
        jsonl_file.write(json_string + '\n')

print("Successfully write to " + output_filename)

TypeError: Object of type Series is not JSON serializable